const appConstants = {
	//Login Screen
	REQUEST_LOGIN: "REQUEST_LOGIN",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_ERROR: "LOGIN_ERROR",

	//List Sreen
	REQUEST_LOAD_STAFF: "REQUEST_LOAD_STAFF",
	LOAD_STAFF_SUCCESS: "LOAD_STAFF_SUCCESS",
	LOAD_STAFF_ERROR: "LOAD_STAFF_ERROR",
	LOAD_REPORTS: "LOAD_REPORTS",
	LOAD_REPORTS_SUCCESS:"LOAD_REPORTS_SUCCESS",
	LOAD_REPORTS_ERROR:"LOAD_REPORTS_ERROR"
}

export default appConstants
