const appConstants = {
	//Login Screen
	REQUEST_LOGIN: "REQUEST_LOGIN",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_ERROR: "LOGIN_ERROR",

	//List Sreen
	REQUEST_LOAD_STAFF: "REQUEST_LOAD_STAFF",
	LOAD_STAFF_SUCCESS: "LOAD_STAFF_SUCCESS",
	LOAD_STAFF_ERROR: "LOAD_STAFF_ERROR",

	//REPORT DETAIL
	REQUEST_GET_REPORT_DETAIL:"REQUEST_GET_REPORT_DETAIL",
	GET_REPORT_DETAIL_SUCCESS:"GET_REPORT_DETAIL_SUCCESS",
	GET_REPORT_DETAIL_ERROR:"GET_REPORT_DETAIL_ERROR",

	//FILE LIST
	REQUEST_GET_FILE_LIST:"REQUEST_GET_FILE_LIST",
	GET_FILE_LIST_SUCCESS:"GET_FILE_LIST_SUCCESS",
	GET_FILE_LIST_ERROR:"GET_FILE_LIST_ERROR",

	//STATUS HISTORY
	REQUEST_GET_STATUS_HISTORY:"REQUEST_GET_STATUS_HISTORY",
	GET_STATUS_HISTORY_SUCCESS:"GET_STATUS_HISTORY_SUCCESS",
	GET_STATUS_HISTORY_ERORR:"GET_STATUS_HISTORY_ERROR"

	LOAD_REPORTS: "LOAD_REPORTS",
	LOAD_REPORTS_SUCCESS:"LOAD_REPORTS_SUCCESS",
	LOAD_REPORTS_ERROR:"LOAD_REPORTS_ERROR"

}



export default appConstants
